### GET 
GET http://localhost:4004/odata/v4/hospital/Patients


### POST
POST http://localhost:4004/odata/v4/hospital/Patients
Content-Type: application/json

{
  "ID": "aaaa1111-bbbb-2222-cccc-3333dddd4444",
  "firstName": "Karan",
  "lastName": "Pavhane",
  "dateOfBirth": "1995-05-12",
  "gender": "Male",
  "phone": "+91-9876543210",
  "email": "karan.pavhane@example.com",
  "address": "Pune, India",
  "createdAt": "2025-08-19T10:30:00Z",
  "modifiedAt": "2025-08-19T10:30:00Z"
}
